### PR TITLE
Update Testflight iOS SDK to version 2.2.1.

### LINKED ISSUE #10: Update iOS SDK and add instructions for tracking
If you would like to have your testers' sessions identified and allow In App Updates: make sure you are using SDK 2.2.0 or later, remove the "iTunesArtwork" file from your build, and re-upload.

See https://www.testflightapp.com/sdk/ios/doc/

### PR DESCRIPTION
**Pull request by jonatansberg**
Fixes #10.

### CODE REVIEW

**Comment by viezel** [comment]
Hi @mrlundis great stuff!!
Would you please update the readme changelog with the new features and change of min sdk. 
Why do we need to change the min sdk to 3.2.0 ?

once readme is updated, I will merge it.

**Comment by jonatansberg** [comment]
@viezel Thanks! 

I had to change the Titanium SDK since I didn't have any older versions of the 2.X series lying around. As far as I know there has't been any major changes to the module API, but I you think that there is a risk of breaking backwards compatibility I can always do a new build against the old 2.1.3 SDK.

Also, completely missed the README in the ios folder, will update that right away.

**Comment by stephenfeather** [comment]
Users cant submit to the app store with older sdks as 2.1.x don't support iOS 7.  Modules might ought to be taking this into account.

**Comment by jonatansberg** [comment]
@sfeather Thats a valid point, although as far as I can tell modules built against older Ti SDK versions work just fine, even on the App Store. 

There where some breaking changes for modules between SDK versions 1.8.x and 2.x, but other than that not much has changed, especially since this module dose not use any other parts of the SDK.

**Comment by viezel** [comment]
Already Pushed #12. Thanks for the PR. Very nice :)

**Pull request closed without merging**
