### PR TITLE
Update DkNappTestflightModule.m

### PR DESCRIPTION
**Pull request by FokkeZB**
Fixes anonymous users showing up in reports:
http://help.testflightapp.com/customer/portal/articles/829863-build-activity-is-showing-anonymous-data

_Note:_ Didn't test it well :)

### CODE REVIEW

**Comment by FokkeZB** [comment]
We need to add a check to only do this in non-production (app store?) builds and in iOS7 users are always anonymous until TestFlightApp has a workaround:

http://help.testflightapp.com/customer/portal/articles/829586-why-is-all-my-sdk-data-showing-up-as-anonymous-

**Comment by viezel** [comment]
no no. If I remember correctly, then SDK 2.X does not use identifier anymore

**Comment by FokkeZB** [comment]
It does, but only for betas: https://testflightapp.com/sdk/ios/doc/

**Comment by FokkeZB** [comment]
Closing for inactivity

**Pull request closed without merging**
